const char* html = 
    "<!DOCTYPE html>"
    "<html lang=\"pt-BR\">"
    "<head>"
    "<meta charset=\"UTF-8\">"
    "<title>Controle Residencial</title>"
    "<style>"
    "  body {"
    "    font-family: Arial, sans-serif;"
    "    background-color: #eef1f4;"
    "    margin: 0;"
    "    padding: 20px;"
    "    color: #333;"
    "  }"
    ""
    "  h1 {"
    "    text-align: center;"
    "    margin-bottom: 30px;"
    "  }"
    ""
    "  .container {"
    "    display: grid;"
    "    grid-template-columns: repeat(auto-fit, minmax(450px, 1fr));"
    "    gap: 20px;"
    "  }"
    ""
    "  .pnl {"
    "    background-color: #fff;"
    "    border-radius: 8px;"
    "    padding: 20px;"
    "    box-shadow: 0 4px 8px rgba(0,0,0,0.1);"
    "  }"
    ""
    "  .pnl h2 {"
    "    margin-top: 0;"
    "    color: #007BFF;"
    "    font-size: 20px;"
    "  }"
    ""
    "  .light {"
    "    margin-bottom: 30px;"
    "    font-size: 25px;"
    "  }"
    ""
    "  .status { font-weight: bold; }"
    ""
    "  .on { color: green; }"
    ""
    "  .off { color: red; }"
    ""
    "  .btn {"
    "    padding: 12px 15px;"
    "    margin-left: 5px;"
    "    font-size: 20px;"
    "    border: none;"
    "    border-radius: 4px;"
    "    cursor: pointer;"
    "    background-color: #007BFF;"
    "    color: white;"
    "  }"
    ""
    "  .btn-temp { width: 80px; height: 70px; font-size: 45px; line-height: 35px; }"
    ""
    "  .lfr { float: right; width: 110px; }"
    ""
    "  .di { display: inline; }"
    ""
    "  .btn:hover { background-color: #0056b3; }"
    ""
    "  .temp {"
    "    font-size: 24px;"
    "    margin: 15px 0;"
    "    color: #555;"
    "  }"
    ""
    "  .btn-alarm { background-color: #dc3545; }"
    ""
    "  .btn-alarm:hover { background-color: #a71d2a; }"
    ""
    "  .alarm {"
    "    font-weight: bold;"
    "    font-size: 18px;"
    "  }"
    ""
    "  .d-none { display: none; }"
    "</style>"
    "</head>"
    "<body>"
    "  <h1>Painel Residencial</h1>"
    "  <div class=\"container\">"
    "    <div class=\"pnl\">"
    "      <h2>Luzes</h2>"
    "      <div class=\"light\">"
    "        Entrada: <span class=\"status %s\">%s</span>"
    "        <form class=\"lfr\" action=\"./entrance_light\"><button class=\"btn\">%s</button></form>"
    "      </div>"
    "      <div class=\"light\">"
    "        Sala: <span class=\"status %s\">%s</span>"
    "        <form class=\"lfr\" action=\"./room_light\"><button class=\"btn\">%s</button></form>"
    "      </div>"
    "      <div class=\"light\">"
    "        Cozinha: <span class=\"status %s\">%s</span>"
    "        <form class=\"lfr\" action=\"./kitchen_light\"><button class=\"btn\">%s</button></form>"
    "      </div>"
    "      <div class=\"light\">"
    "        Quarto: <span class=\"status %s\">%s</span>"
    "        <form class=\"lfr\" action=\"./bedroom_light\"><button class=\"btn\">%s</button></form>"
    "      </div>"
    "    </div>"
    "    <div class=\"pnl\">"
    "      <h2>Aquecedor</h2>"
    "      <div class=\"temp\">Temperatura: <strong>%d</strong>°C</div>"
    "      <center>"
    "        <form class=\"di\" action=\"./temp_inc\"><button class=\"btn btn-temp\">+</button></form>"
    "        <form class=\"di\" action=\"./temp_dec\"><button class=\"btn btn-temp\">-</button></form>"
    "      </center>"
    "    </div>"
    "    <div class=\"pnl\">"
    "      <h2>Alarme</h2>"
    "      <div class=\"alarm %s\">%s</div>"
    "      <br>"
    "      <center class=\"%s\"><form class=\"di\" action=\"./alarm_off\"><button class=\"btn btn-alarm\">Desativar alarme</button></form></center>"
    "    </div>"
    "  </div>"
    ""
    "  <script>"
    "    ("
    "        function(){ setInterval(() => { window.location.href='/'; },8000); }"
    "    )();"
    "  </script>"
    "</body>"
    "</html>";